name: Test KoboCloud

on:
  - pull_request
  - workflow_dispatch

jobs:
  job:
    name: Test the Pull Request
    runs-on: ubuntu-latest
    steps:
        - name: Checkout repository
          uses: actions/checkout@v2
          with:
            path: repo
            
        - name: Test Dropbox
          run: |
            cd repo
            ./local_test.sh dropbox
            
        - name: Test pcloud
          run: |
            cd repo
            ./local_test.sh pcloud
            
        - name: Test GDrive
          run: |
            cd repo
            ./local_test.sh gdrive
            
        - name: Test Box
          run: |
            cd repo
            ./local_test.sh box
        
        - name: Test Nextcloud
          run: |
            cd repo
            ./local_test.sh nextcloud
            
        - name: Test Nextcloud - path
          run: |
            cd repo
            ./local_test.sh nextcloudpath
            
        - name: Test Nextcloud - subdir
          run: |
            cd repo
            ./local_test.sh nextcloudsubdir
            
        - name: Test Nextcloud - subdir path
          run: |
            cd repo
            ./local_test.sh nextcloudsubdirpath
            
        - name: Test GDrive + deletion
          run: |
            cd repo
            ./local_test.sh gdrive true
            
